### ISSUE TITLE
Set custom selected options after loading the tree

### ISSUE THREAD

**Issue by msaah85** [patosai/tree-multiselect.js#10]
Hello,
How i can set my custom selected options after loading the tree?

Thanks

**Comment by patosai** [comment]
Do you mean checking specific options after loading, or adding options?

**Comment by msaah85** [comment]
I only need to set value for every checkbox control inside the tree
Thanks

**Comment by patosai** [comment]
You have to render the HTML with the option value. See the demo. You're not supposed to modify anything inside the tree-multiselect manually.
