### ISSUE TITLE
Adding "Select All" and "De Select All"

### ISSUE THREAD

**Issue by dclarke83** [patosai/tree-multiselect.js#12]
It would be really helpful to have methods to be able to select all and select none. I tried to achieve this (see below hacky code), but the information doesn't seem to be saved:
             
$("#btnSelectAll").on('click',function() {
                    event.preventDefault();
                    $("#PromptPanel1_treeviewCommentCodes > option").each(function(){
                        $(this).attr('selected','selected');
                    });
                    $(".tree-multiselect input").each(function(){
                        $(this).attr('checked','checked');
                    });                    
                });
                
                $("#btnDeSelectAll").on('click',function() {
                    event.preventDefault();
                    $("#PromptPanel1_treeviewCommentCodes > option").removeAttr("selected");
                    $(".tree-multiselect input:checked").removeAttr("checked");
                });

**Comment by msaah85** [comment]
Thanks a lot for your support,

Can i set value for every checkboxin the tree?
<input type="checkbox" value="1" />
This will help me if i want to set checked to determine nodes..

Thanks

**Comment by patosai** [comment]
Could you wrap all your options with a section? Then you could just check/uncheck one box.

**Comment by msaah85** [comment]
I tried to set value attribute inside addCheckboxes() function by the followng line
`$checkbox.attr('value', $targets.data('value'));`

`function addCheckboxes($selectionContainer, options) {
        var $checkbox = $('<input />', { type: 'checkbox', value: '' });
        if (options.freeze) {
            $checkbox.attr('disabled', 'disabled');
        }
        var $targets = null;
        if (options.onlyBatchSelection) {
            $targets = $selectionContainer.find("div.title");
        } else if (options.allowBatchSelection) {
            $targets = $selectionContainer.find("div.title, div.item");
        } else {
            $targets = $selectionContainer.find("div.item");
        }

        **$checkbox.attr('value', $targets.attr('data-value'));**

        $checkbox.prependTo($targets);
        $selectionContainer.find('input[type=checkbox]').click(function (e) {
            e.stopPropagation();
        });
    }`

but didnt get the agood result.

can you help me to put value of every option to related checkbox.
Thank you very much

**Comment by dclarke83** [comment]
Thanks for replying patosai!
If possible, I would prefer not to wrap everything in an outer section - I am already using sections and don't want to show all sections open by default (which I would probably have to do, if I had a single outer section, otherwise my users wouldn't see the options available to them).

![image](https://cloud.githubusercontent.com/assets/18419752/14488144/939e7214-015e-11e6-8b3d-9f5f9291fde6.png)

**Comment by patosai** [comment]
Ok I can it being useful. Hang on.

**Comment by patosai** [comment]
f9997b0c8cc878cfc1b74757ab0c6b453d8f0003 should do it. I'm not sure how to best style it; let me know what you think.

**Comment by dclarke83** [comment]
Functionally, what you have added is perfect - thank you for being so accommodating! For my application, I would like to style the links as bootstrap btns - maybe the css classes used for the spans can be an option?. Is it possible to make the "Select All" and "Un Select All" text variable (via options)? I would like to localize it so that the appropriate translation may be displayed for the end user's language.

**Comment by patosai** [comment]
You can modify the source yourself for the bootstrap buttons. I think having the text as an option is a good idea.
