### ISSUE TITLE
refresh option

### ISSUE THREAD

**Issue by keerthanaRam** [patosai/tree-multiselect.js#13]
Hi Patosai... This is a nice application... in my program first i will populate tree with some pre selected options and then there is a button like reset, on clicking that i want to refresh my page without any pre selected options....can u please provide any option like refresh?

**Comment by patosai** [comment]
What's the difference between that and unselecting all?

**Comment by keerthanaRam** [comment]
yeah you are right... but the requirement has now changed... on clicking the refresh i need to select different values dynamically not the one which is selected first.... Thanks for the reply

**Comment by patosai** [comment]
Is this issue resolved?

**Comment by keerthanaRam** [comment]
is there any option to change our selected items on clicking a button?

**Comment by patosai** [comment]
No, unless you mean the checkboxes.

**Comment by keerthanaRam** [comment]
ok thankyou

**Comment by patosai** [comment]
That does seem like a decent idea though, having buttons that select specific sets of options.

**Comment by mtabdar** [comment]
i agree. it would be nice to have a button beside "select all" and "none" to select specific sets of options.
