### ISSUE TITLE
the number more than 2000,the speed is very slowly,ie and firefox brower is died

### ISSUE THREAD

**Issue by lehe2** [patosai/tree-multiselect.js#16]

**Comment by patosai** [comment]
I believe this has to do with the number of event handlers that are attached to the DOM.

**Comment by lehe2** [comment]
ok,thanks,it already do work well.

**Comment by 007manu007** [comment]
Hi,

Suppose if there are more items like (2000 or more than 3000) and we click "seelct all" or "unselect all" then Browser get freeze. Is there a way to solve this problem?

**Comment by patosai** [comment]
So I've cleaned up a fair amount of the event handlers, so things should be faster. Try 47eaec5e4e1281df84fa3f04badaf2893f628fda (v1.18.0)

That being said, I wonder why you've got 2000 nodes in your select? That seems like a lot of options for the user.

**Comment by lehe2** [comment]
For example, in such a scenario, a device has a lot of equipment account

**Comment by lehe2** [comment]
I rewrite it myself, the speed seems to be a little better than you
