### ISSUE TITLE
When a value field is a digit number, it's not displayed in the 'selected' div

### ISSUE THREAD

**Issue by garaud** [patosai/tree-multiselect.js#2]
Hi,

I don't see the selected field at the right side of my browser when the value field is a number.

```html
  <option value="10712" data-section="107">10712</option>
  <option value="10796" data-section="107">10796</option>
```

Thanks. Cheers,
Damien G.

**Comment by patosai** [comment]
jQuery .data() was automatically converting the values into integers. I replaced it with attr() which doesn't do automatic conversions, so everything should be fine now.

Thanks mate.

**Comment by garaud** [comment]
Great! Works perfectly fine.
Thanks you.
