### ISSUE TITLE
no search?

### ISSUE THREAD

**Issue by cdwmhcc** [patosai/tree-multiselect.js#21]
no search?

**Comment by anup-kubade** [comment]
Hey team,
Can you please implement the search functionality.
More over the component reacts very slow when the total elements goes around 5000.
The component works decent with 1000 elements.

**Comment by iversonlin330** [comment]
I also need search.
How can I do it myself  by easy way?

**Comment by patosai** [comment]
Pull requests welcome.

**Comment by pratikthakare777** [comment]
I am trying to implement search functionality. After search i am unable to update Tree Multi-select.  Is there any way to update Tree. I want reload/refresh tree that's it.

**Comment by pratikthakare777** [comment]
hey got solution just need to call this `  $select.treeMultiselect({ enableSelectAll: true, sortable: true });`

**Comment by patosai** [comment]
Implemented in c7ab72b256994f0b56142e6e7ccfc09760160e4b

**Comment by pratikthakare777** [comment]
Thanks For search functionality . Its really help me lot. By the way side by side I have implemented that functionality same like you have done. @patosai

**Comment by patosai** [comment]
A pull request would have been nice.

**Comment by pratikthakare777** [comment]
Hey I tried your search its work on value of select option (i.e. <option value="Value Data">Text Data</option>) not on text some times value and text are different. Is it configurable ? @patosai

**Comment by patosai** [comment]
Yes, it searches value, text, and section name. Not configurable but it is easy to do so.

**Comment by patosai** [comment]
And it is done.
