### ISSUE TITLE
Predefined selection do not repopulate after select element is recreated programaticaly

### ISSUE THREAD

**Issue by madamec63** [patosai/tree-multiselect.js#23]
Here is the scenario:
A select element is created in JS code like this:

    someSelect = $('<select id="someSelect" multiple="multiple"></select>');
    for(var key in data.result.somedata){
         group = data.result.somedata[key];
         $.each(group, function() {
              someSelect.append('<option value="' + this +
                     '" data-section="' + key + '">' + this + '</option>');
         });
     }
then later in the code pre-selected options (based on their presence in `cols` array) are marked and tree-multiselect is created:

	$("div#graphDataBox").append(someSelect);
	$("select#someSelect option").removeAttr("selected");
	$("div.tree-multiselect").remove();
	$.each($("select#someSelect option"), function() {
		if(cols.indexOf($(this).val()) > -1) {
			$(this).attr("selected", "selected");
		}
	});

	$("select#strategies").treeMultiselect({startCollapsed: true});

Everything works like a charm at the first page load.
Once the code retrieves the new set of `cols` via an Ajax request from the back-end repopulation of the tree-multiselect pre-selections fails. I checked the someSelect options are correwctly mark as selected (done in $.each function) when the data come back from the Ajax call.

What do I miss when cleaning up before rebuilding?

Thank you

Martin

**Comment by madamec63** [comment]
I was able to make it work but had to scrape and recreate everything I derived the tree-multiselect from. Any attempt to recycle what I built at the page-load failed for some reason.
Therefore, even I am not blocked by the issue anymore it might be worth checking this scenario described above and try to reproduce the problem.

**Comment by patosai** [comment]
What did you do after the AJAX call?
