### ISSUE TITLE
just one option with no child

### ISSUE THREAD

**Issue by andisulistyonugroho** [patosai/tree-multiselect.js#24]
Hi @patosai, how to do if I want to have only one option with no child?
example

```
1.Menu A
- Sub Menu A.1
- Sub Menu A.2
2. Menu B
3. Menu C
4. Menu D
- Sub Menu D.2
```

**Comment by patosai** [comment]
I'm not understanding your question. Where are the `select` options in those menus?

**Comment by andisulistyonugroho** [comment]
Sorry for asking an unclear question, I understand that the hierarchy of `div.selection` is `div.title` and `div.item`, I just wondering is it possible to have only `div.title` for option Menu B and Menu C on the select option below without displaying `div.item`?

```
HTML
<select id="demo" style="margin: 0px auto 1em; display: block;" multiple="multiple">
  <option value="submenuA1" data-section="Menu A">Sub Menu A.1</option>
  <option value="submenuA2" data-section="Menu A">Sub Menu A.2</option>
  <option value="menuB" data-section="Menu B">Menu B</option>
  <option value="menuC" data-section="Menu C">Menu C</option>
  <option value="submenuD2" data-section="Menu D">Sub Menu D.2</option>
</select>
```

```
Javascript
$("select#demo").treeMultiselect({
        sortable: true,
        hideSidePanel: true
});
```

**Comment by patosai** [comment]
If you're wondering if you can make a section with no options under it, then no.
