### ISSUE TITLE
Set value to parent node

### ISSUE THREAD

**Issue by sredXNY** [patosai/tree-multiselect.js#29]
Hey, I'm using this widget and it's really good. But now I'm wondering, how can I set the value for a parent node? I mean, I have this:

```
<option data-section="All/Image" value="someValue">HD</option>
<option data-section="All/Image" value="someValue">Series</option>
<option data-section="All/Image/Books" value="someValue">Dutch</option>
<option data-section="All/Image/Books" value="someValue">English</option>
```

So, its displayed as:
|---All
|-------Image
|-------------HD
|-------------Series
|-------------Books
|-------------------Dutch
|-------------------English

And it's going well until here, but now, How I set a value only for the _Image_ option? when the users select Image I want to send a value for it

**Comment by patosai** [comment]
There's no way to do that right now.

**Comment by RashidShamsi** [comment]
@patosai 
after several years, is this possible now to get the value of Parent node??
