### ISSUE TITLE
Collapse after clearing search box

### ISSUE THREAD

**Issue by chamster** [patosai/tree-multiselect.js#32]
Great plugin. Thanks. When I type something into the search box, the nodes that contain matching items are expanded and displayed. Then I can select one of the items. But then when I clear the search box, I'm left with all the nodes in the whole tree expanded. I have lots of nodes so that makes it pretty difficult to browse the tree. It would be better if, after clearing the search box, all nodes collapsed again like they are when the page loads. Or, another option might be to have a button to collapse all. Thanks.

**Comment by hubertrogers** [comment]
I really really really really would like it to work like this as well. And agreed, great plugin!

**Comment by patosai** [comment]
Please check out v2.1.4 (61b48e8ff4310adef6fb62383dae53a01bacd1f1) and tell me what you think.

**Comment by patosai** [comment]
Or check out v2.1.5 (58d1129c8f0a2ef6674b49721b16b6d412b8c0f9), this one expands all search results when searching and returns to the previous state when the box is empty.

**Comment by chamster** [comment]
Perfect! Nice job! Thanks!
