### ISSUE TITLE
Don't have IE9 support for closing of selected node 

### ISSUE THREAD

**Issue by pratikthakare777** [patosai/tree-multiselect.js#34]
Is it possible alternative implantation of closing of selected node for IE9. I have tested in IE 9. I am unable to removed selected not in IE9.

**Comment by ihabsalem** [comment]
Kindly paste the below code above node.remove() in the js file, then it should work fine 

if (!('remove' in Element.prototype)) {
    Element.prototype.remove = function() {
        if (this.parentNode) {
            this.parentNode.removeChild(this);
        }
    };
}
