### ISSUE TITLE
data-section plus prefix doesn't change to minus when opened from a search

### ISSUE THREAD

**Issue by Nils2027** [patosai/tree-multiselect.js#35]
The plus prefix of a data-section only changes when clicked directly. When you type something search, all the relevant data-sections open themselfes but without changeing the prefix to a minus. When you click the data-section after a search, it does change, but the wrong way around. 

The tree is initialized with the parameter startCollapsed: true

**Comment by patosai** [comment]
v2.1.4 (61b48e8ff4310adef6fb62383dae53a01bacd1f1)
