### ISSUE TITLE
Issue in IE while removing nodes and batch select.

### ISSUE THREAD

**Issue by leoaraguas** [patosai/tree-multiselect.js#37]
Hi, I got an error in IE while it tries to remove the nodes.

Fixed it by replacing `node.remove();`  by `$(node).remove(); `  

Also, (and just as a suggestion), the event that can be captured for **selectionContainer** can be '**click**'. In this way, IE will trigger the event even when the checkbox properties **indeterminate** is **true** and **checked** is **false**.

Great work! and hope this helps to you 

Cheers!

Leo

**Comment by patosai** [comment]
Ok, some other people have commented on the IE `node.remove()` thing so I'll fix it for now. As for the `click` event, can you explain that more? Thanks.

**Comment by leoaraguas** [comment]
When you click on a node that is `indeterminate = true`, IE _doesn't triggers the OnChange event_. 

This means that all the code involved in the event listener for **selectionContainer** is not going to run. 

However, if you change the event to click, it will make the deal. Basically when you click the checkbox you are changing the value, so it will behave as expected in any browser. 

Make sense ?

Cheers!

Leo

**Comment by patosai** [comment]
c7c9acaf84762fe91781a1f1b51856c59d8c8443
