### ISSUE TITLE
Reload Options @ ajax response

### ISSUE THREAD

**Issue by saif-hmk** [patosai/tree-multiselect.js#39]
All those things worked well at page loading, 
but I want to append options from ajax response.
But 'tree-multiselect' div is not reloading/refreshing.
Could you help me to solve this problem or add an example to your site...?

Thanking you,
SAIF

**Comment by saif-hmk** [comment]
![reload options issue](https://user-images.githubusercontent.com/8227703/26922457-fe6862e6-4c60-11e7-982b-db4859585552.PNG)

**Comment by patosai** [comment]
Right now there's no way to do anything dynamically.

**Comment by patosai** [comment]
Also, your website has a PHP error.
`Fatal error: Uncaught exception 'wfWAFStorageFileException' with message 'Unable to verify temporary file contents for atomic writing.' in /home/preservationassi/public_html/wp-content/plugins/wordfence/vendor/wordfence/wf-waf/src/lib/storage/file.php:30 Stack trace: #0 /home/preservationassi/public_html/wp-content/plugins/wordfence/vendor/wordfence/wf-waf/src/lib/storage/file.php(497): wfWAFStorageFile::atomicFilePutContents('/home/preservat...', '<?php exit('Acc...') #1 [internal function]: wfWAFStorageFile->saveConfig() #2 {main} thrown in /home/preservationassi/public_html/wp-content/plugins/wordfence/vendor/wordfence/wf-waf/src/lib/storage/file.php on line 30`

**Comment by saif-hmk** [comment]
Sorry,
I think PHP issue is not mine.

**Comment by saif-hmk** [comment]
Thanks for your quick response...

**Comment by patosai** [comment]
Done.

9392cbd7e1d41e8dae812bf9dbfdd53f8031b66a

**Comment by vijaykotha** [comment]
Hi patosai,

I am getting the error .reload is not a function. Could anyone help me out. Is there any way to update the tree with new options

**Comment by patosai** [comment]
You're probably calling `reload()` on an array. If you read the README you'll see the problem.

**Comment by vijaykotha** [comment]
I am not calling reload() on an array.. I am doing this way.. please look at this

var gridTree = $("#treeSelectForGrid").treeMultiselect({
    			searchable : true,
    			searchParams: ['section', 'text'],
    			sectionDelimiter : '.',
    			sortable: true});
 this.treeSelectForGrid = gridTree[0];

In some other method I am doing this

var treeSelectForGrid = this.treeSelectForGrid;
treeSelectForGrid.remove();
treeSelectForGrid.reload();

So at this point it is throwing error reload is not a function
