### ISSUE TITLE
Construct nested structure based on parent

### ISSUE THREAD

**Issue by skarampatakis** [patosai/tree-multiselect.js#41]
Hi,
Congrats for your project, it is really helpful. 

However I have a question. Would it be possible to construct nested structure, only by giving the parent's node value and not the full path? It would be really helpful in situations where is hard to get the full path. 

Thank you in advance.

**Comment by skarampatakis** [comment]
Thank you for your response. Since it is a select input I don't think there are cases where the value is the same. At least for my case I am sure that all option values are different. 

However I changed my api behaviour server side, so now I almost have what I requested. Maybe it also faster to do so. But I think it would be a good adition.

**Comment by patosai** [comment]
Ah, I thought you meant having duplicate section names. I suppose that would be nice, though I think the current use case is good enough.
