### ISSUE TITLE
Object doesn't support property or method 'remove' - internet explorer

### ISSUE THREAD

**Issue by szabotomi** [patosai/tree-multiselect.js#42]
Hello I got this error "Object doesn't support property or method 'remove' "
 using this plugin in internet explorer,
this happened at:

` if (node) {
      node.remove();`
at line 579.
I fixed this error by changing this line with:
`node.parentNode.removeChild(node);`

Thanks,
Tamas

**Comment by patosai** [comment]
I believe this is already fixed.
