### ISSUE TITLE
how to select item with js?

### ISSUE THREAD

**Issue by erichow** [patosai/tree-multiselect.js#46]
I want implement radio function,  when user click optgroup2's item, optgroup1's items will unchecked.
how can i do this??

**Comment by patosai** [comment]
There's no native way to select an item with JavaScript right now.

**Comment by caco13** [comment]
@erichow, I'm using selenium to automate selection of options in my functional tests. Maybe it can help you. I'm selecting an option, getting the `div` tag and its `data-value` attribute. The value of `data-value` attribute is the original option value of the select tab.

**Comment by Amerlander** [comment]
You can simulate a click with jquery:
` element = $('.tree-multiselect  .item[data-value="testfield"] > input'); 
 element.click();`

I deselect all items with (enable "deselect all" in options first)
`$('.unselect-all').click();`
and then run trough an array to select all my items.
