### ISSUE TITLE
Enhancement suggestion - disabled prop

### ISSUE THREAD

**Issue by MichaelBieniek** [patosai/tree-multiselect.js#47]
Locally, I've extended your library to handle option[disabled=true], rendering a disabled, unselectable input checkbox. Haven't gotten around to propagating that up to parent checkboxes, but nonetheless a useful feature imo.

**Comment by patosai** [comment]
Sounds like a good idea.

**Comment by patosai** [comment]
I decided to go with the `readonly` prop since the `disabled` prop doesn't actually send values in a form.
