### ISSUE TITLE
Limit the height of the selected options

### ISSUE THREAD

**Issue by Luisfermp18** [patosai/tree-multiselect.js#49]
Good Morning,

I am trying to limit the height of the column of selected elements, in order to make it scrollable, I have come to use in the inspector even the element.style selector, forcing the height even with important.

I have not been able to make that listing fit the desired height.

Could you help me?

Thx so much!
Luisfermp

**Comment by patosai** [comment]
Ok, there was an extra `display` attribute that shouldn't have been there. That's fixed now, all you need to do is add a `height` attribute to the `.selected` and `selections` CSS rule.
