### ISSUE TITLE
hidden original select element does not have it's change event triggered

### ISSUE THREAD

**Issue by amackey** [patosai/tree-multiselect.js#5]
When jqOriginalSelect has .val(selected) called on it, the element's change event is not triggered because it's hidden; need to explicitly call .change() after .val(selected).

**Comment by patosai** [comment]
Cool, this should be pretty simple to fix.

**Comment by patosai** [comment]
82631ffb015dd00e6295b676e45ddbbb468a9222 should do this.

**Comment by amackey** [comment]
agreed, thanks! -Aaron
