### ISSUE TITLE
do not selected default

### ISSUE THREAD

**Issue by lscgzwd** [patosai/tree-multiselect.js#51]
```
<select>
<option selected></option>
<option selected></option>
<option selected></option>
</select>
```
The tree not checked those items which has selected attribute

**Comment by patosai** [comment]
What version is this? I'm not seeing this problem on the latest version.

**Comment by lscgzwd** [comment]
I'm use the bower. 
"tree-multiselect": "^2.4.1"

**Comment by patosai** [comment]
Do you have a screenshot?

**Comment by lscgzwd** [comment]
![image](https://github.com/lscgzwd/static/blob/master/github.png)

**Comment by lscgzwd** [comment]
only select the last item every time.

**Comment by patosai** [comment]
Your data-index is 1 for every item, that's why only the last one is being selected.

**Comment by lscgzwd** [comment]
测试结果没有修复，
bower.json
```
"tree-multiselect": "^2.4.2"
```
依旧只选择了最后一个

**Comment by patosai** [comment]
2.4.3應該更新，我這邊有選到全部的
![screenshot from 2017-11-02 02 20 39](https://user-images.githubusercontent.com/5304405/32312487-7475f620-bf74-11e7-8341-913e68d2b2c6.png)

**Comment by lscgzwd** [comment]
现在默认选中了所有
![](https://github.com/lscgzwd/static/blob/master/15096104218308.png)

**Comment by patosai** [comment]
2.5.0有改這，`data-index`和`selected`兩個要加才會出現

請問為什麼每個option有加`data-index=1`？不同的`data-index`才有用

**Comment by lscgzwd** [comment]
看你的描述data-index实际用来做排序用，在一个系统中，比如菜单，可能默认大家的排序都是1，系统设计很多时候会设计成 order by `sort`, `id` asc    本身`sort` 就可能存在重复的情况，并且我试了现在的代码，就算把data-index 的值 换成数据库主键，也就是id，确认不重复的情况也是有BUG的，要么全选所有，要么就是只选择最后一个。

**Comment by patosai** [comment]
了解，所以bug現在沒有了吧？

**Comment by lscgzwd** [comment]
BUG在的，只是我没用data-index了，

**Comment by patosai** [comment]
2.5.0應該有修理bug.

**Comment by lscgzwd** [comment]
fixed
