### ISSUE TITLE
Request: Single Select

### ISSUE THREAD

**Issue by MikeMelendez21** [patosai/tree-multiselect.js#53]
I love this control.  Recently I came upon a situation where I needed to have cascading dropdowns so a user can navigate a hierarchy down to a single record.  I thought perhaps instead of these cascading dropdowns which is hard to navigate I would use your multi-select tree.  It works perfect for my needs including searching, the only problem is I want to limit the user to a single selection.  

So I'm requesting the ability to include a config property that lets me specify a limit to the number of selected items.  That way I could specify 1 for a single select, or 3 for a multi-select with a limit of 3 selected and no more.

**Comment by patosai** [comment]
3c6f8b91ae3a00ea75e6efebfa9818a654bab72e

v2.5.1, `maxSelections` is your friend. Check it out.
