### ISSUE TITLE
Is there a way to only allow select at lowest level?

### ISSUE THREAD

**Issue by WincingDevil** [patosai/tree-multiselect.js#56]
We are using v1.17, and we only want to select at the deepest level of the tree as per this photoshopped mock-up.  Is this possible in 1.17?  If not is it available in V2.5.0?
![multiselect-mockup](https://user-images.githubusercontent.com/6363357/34311199-3bd73a62-e72a-11e7-975c-3e3cfcb6910d.jpg)

The way it is now:
![multiselect-as-is](https://user-images.githubusercontent.com/6363357/34311223-601227de-e72a-11e7-962d-023203b11b05.jpg)

**Comment by patosai** [comment]
Yes, set the `allowBatchSelection` param to `false`.

**Comment by WincingDevil** [comment]
Thanks for the quick response. Is this adjustable to perhaps the bottom 2 levels?

**Comment by patosai** [comment]
No, it's an on or off option.
