### ISSUE TITLE
How to get entire selected data on button click ?

### ISSUE THREAD

**Issue by abrarakazi** [patosai/tree-multiselect.js#57]
I am selecting multiple checkboxes and i have a submit button where i want to get the selected data. How do i do that ? Is there a inbuilt function that i am missing ?

**Comment by patosai** [comment]
The original `select` is modified so nothing needs to be done.

**Comment by abrarakazi** [comment]
i didnt get your answer. what is the way to get the selected data ? 

is it $(select).val() ?? 

i want to post the selected data to my controller.

**Comment by patosai** [comment]
Just get the selected items from the original `select` element, the one you called `treeMultiselect()` on, any way you want.

**Comment by noiwid** [comment]
Hi, unfortunatly, this method don't preserve order :(
