### ISSUE TITLE
Uncaught TypeError: $(...).treeMultiselect is not a function in jquery functions.

### ISSUE THREAD

**Issue by abrarakazi** [patosai/tree-multiselect.js#58]
'''        $("#selectColumns").treeMultiselect({
            allowBatchSelection: false,
            startCollapsed: false
        });
// The above code works fine but the below code doesnt work and throws error : 
Uncaught TypeError: $(...).treeMultiselect is not a function in jquery functions.

function UnCollapse()  // jquery function
    {
        $("#selectColumns").treeMultiselect({
            allowBatchSelection: false,
            startCollapsed: false
        });
    }
'''

**Comment by abrarakazi** [comment]
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
<link href="~/Content/jquery.tree-multiselect.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>
<script src="~/Scripts/jquery.tree-multiselect.min.js"></script>

**Comment by patosai** [comment]
I'm guessing you are calling `UnCollapse` before the window is ready.

**Comment by abrarakazi** [comment]
no i am not. any .treemultiselect function inside jquery functions gives the same error
