### ISSUE TITLE
Can select a section without selecting all the childs?

### ISSUE THREAD

**Issue by fedegara** [patosai/tree-multiselect.js#6]
Can select a section without selecting all the child's?

i have this hierarchy:

Drinks
    ->Whisky
        ->Irish
        ->Scotch
    ->Soda
        ->Coca Cola

I need to select section "Whisky" without selecting irish and scotch.
Is any option or attribute i can use for this?

**Comment by patosai** [comment]
That should work out of the box, do you have an example of some sort?

**Comment by fedegara** [comment]
not really, i search in others tree but nobody have that option. Discard this and thank you so much for the fast reply

**Comment by patosai** [comment]
So did it have what you wanted?

**Comment by fedegara** [comment]
yes your library is perfect i have a bad concept
