### ISSUE TITLE
Select all element acording to the search box

### ISSUE THREAD

**Issue by meyer59** [patosai/tree-multiselect.js#61]
Hi,
first, thanks for the great package.
When the tree is filtered by the search box and all the tree is selected, the search doesn't apply to the selected node. 
Only the node filtered should be selected, the screenshot below shows the bug on the demo website:
![image](https://user-images.githubusercontent.com/9505463/38800222-009e0c54-4167-11e8-8e0b-9860b31a6b33.png)
Thanks for the help

**Comment by patosai** [comment]
Seems to be fixed in 2.5.2 5a9f8167b2d19aa018ee390e70b5657a098105fe
