### ISSUE TITLE
Bower configuration broken

### ISSUE THREAD

**Issue by champ** [patosai/tree-multiselect.js#62]
Hi,

The Bower configuration was broken in [this commit](https://github.com/patosai/tree-multiselect.js/commit/c8badfcdda0de559353a078d60191c1340774348): there is a comma missing in the `ignore` section before the last entry (`!LICENSE`).

```json
"ignore": [
    "*",
    "!dist/",
    "!src/",
    "!package.json"
    "!LICENSE"
  ],```

By the way, great plugin!

**Comment by patosai** [comment]
Good catch, just fixed this.

**Comment by champ** [comment]
Quick fix @patosai! It still fails though since bower uses Git tags. Are you planning on pushing a new tag - `5.2.1` or retag version `5.2.0` to make it available in bower?

**Comment by patosai** [comment]
Just updated the 2.5.2 tag, sorry about that!
