### ISSUE TITLE
unselect iteme

### ISSUE THREAD

**Issue by mlezcano1985** [patosai/tree-multiselect.js#65]
Hi, I need to deselect an element using the code. Using jquery I unselect the option tag and change selected value of the item instance. For example:
```
rollback.forEach((item) => {
   item.node.firstChild.checked = false;
    $(`#estaciones option#${item.value}`).prop('selected', false);
 });
```
But when `onChange` callback is execute again the item come in `allSelectedItems` paramter. There is any way to unselect an item using this plugin??

Greetings

**Comment by patosai** [comment]
You need to fire the 'click' event. So I guess it would look something like

```
rollback.forEach((item) => {
    $(`#estaciones option#${item.value} input[type=checkbox]`).click();
 });
```
