### ISSUE TITLE
Freeze causing confusion to end user

### ISSUE THREAD

**Issue by lovegupta** [patosai/tree-multiselect.js#67]
When i use freeze: true option then component gets disabled which is great but it shows parents selected while they don't have any child as selected.
Below is the code-

`
$(document).ready(function() { $("#<%= id_namespace + Constants.FIELD_OA_CONDITIONS %> ").treeMultiselect({ searchable: true, startCollapsed: true, freeze: true, searchParams: ['text', 'description'] }); });`

And it renders the output as

![1](https://user-images.githubusercontent.com/42310549/46820076-4c3f5a00-cd53-11e8-80cf-ca4233330f62.jpg)

If I expand the individual trees

![2](https://user-images.githubusercontent.com/42310549/46820086-506b7780-cd53-11e8-9fcf-560b2758b3d3.jpg)

So if you notice then nothing in second tree is selected still I have Down Payment checkbox as selected. While I checked the rendered HTML, the checkbox is actually not checked

![3](https://user-images.githubusercontent.com/42310549/46820092-53fefe80-cd53-11e8-8348-2c29b3796aa0.jpg)

But it appears on UI that all children of Down Payment parent are checked. Is it a bug or it is how it is meant to work. It is causing confusion for end user because parent is checked means all children are selected.

Same is behavior in all browsers (I checked IE, Firefox, Chrome)

**Comment by patosai** [comment]
Thanks for catching this, v2.6.1 should fix this.
