### ISSUE TITLE
Reload but keep the selected values.

### ISSUE THREAD

**Issue by fastesol** [patosai/tree-multiselect.js#68]
Hi there, one of the best plugin so far I'm using for my projects. one question, is there a way to keep the selected values as it is when calling the reload function? if no, I think, it is much needed feature (just a thought).

Thank you!

**Comment by patosai** [comment]
If you need the same values, why reload?

**Comment by fastesol** [comment]
Let say I want to add another option through jQuery. and call a refresh()

**Comment by patosai** [comment]
I finally got around to this in 2.6.0
