### ISSUE TITLE
Simple list

### ISSUE THREAD

**Issue by lcastells88** [patosai/tree-multiselect.js#69]
How can I show a simple list, I mean show the list of elements without sections.

**Comment by patosai** [comment]
Just leave `data-section` empty, or don't add the attribute.

**Comment by lcastells88** [comment]
Thank you, but I just did that and the result is what I show you in the image. Keeps the checkbox but no name.
![capture](https://user-images.githubusercontent.com/33266680/52430513-41fc5500-2ad4-11e9-829c-90a760923339.png)

**Comment by patosai** [comment]
I just tried it with no attribute, and I got this
![2019-02-11 19-33-22](https://user-images.githubusercontent.com/5304405/52609948-ec0d1180-2e33-11e9-9eae-b744c899d107.png)
.
