### ISSUE TITLE
Have it not apply to a certain select list

### ISSUE THREAD

**Issue by netbandit** [patosai/tree-multiselect.js#7]
Hey there,

Great component - I had a simple question.. the component works great on the list that I want converted into a multi-select tree.  I have another select list that I do not want converted into a multi-select tree.. so how do I make it so that shows as a normal select drop-down list?

thanks in advance

**Comment by netbandit** [comment]
I should add.. that

**Comment by patosai** [comment]
Just change your selector.

**Comment by newzen** [comment]
Hey,
Great job. Have a issue with it http://jsfiddle.net/newzen/nftdvyk4/3/ all checked but just a few are in the source option.

any help will be appreciated, thanks
