### ISSUE TITLE
side panel issue

### ISSUE THREAD

**Issue by mtabdar** [patosai/tree-multiselect.js#71]
hi again
all is great with the tree but i think the side panel could be more flexible. for example why is it not actually "hid" when you set hideSidePanel to true?
or why is it always on the right, i like it be placed somewhere else, below the tree for example!

**Comment by patosai** [comment]
You can modify the position of the sidebar if you modify the css.

As for the "hid" part, what do you mean?

**Comment by mtabdar** [comment]
thanks for the reply
let me clarify myself. i mean there is a built in option "hideSidePanel" in the js, but when i set it to true, (without making any changes to css), the selected options list disappears but its container is visible. i think it would be much better if the container also disappear.
and could you please show me how to change the css to change the position of sidepanel?

**Comment by patosai** [comment]
Sorry for the delay. I just fixed the sass compilation process, so you should be able to run `grunt sass` to build the css. Change `sass/style.scss` to your liking.

It's true, the container still exists when the option is enabled, but there's nothing inside. That could change.
