### ISSUE TITLE
Dynamic data

### ISSUE THREAD

**Issue by lcastells88** [patosai/tree-multiselect.js#72]
Hello, by chance you have a version of this plugin but with the dynamic data. Thanks.

**Comment by patosai** [comment]
What do you mean by dynamic data?

**Comment by lcastells88** [comment]
Thanks, but what I mean is that I could pass a json with the structure and build the tree.

**Comment by patosai** [comment]
The very first version of the plugin had this, but it's no more. You have to have the select element in the DOM.
