### ISSUE TITLE
Unable to use onChange function

### ISSUE THREAD

**Issue by allphat** [patosai/tree-multiselect.js#73]
I tried to use your example with the definition of a function for the onChange event:

function treeOnChange(allSelectedItems, addedItems, removedItems) {
  console.log("something changed!");
}

$("select").treeMultiselect({
  onChange: treeOnChange,
  startCollapsed: true
});

But event does not seem to be fired

**Comment by patosai** [comment]
What browser are you using?

**Comment by allphat** [comment]
I was using chromium on mac (maybe that’s why?)
