### ISSUE TITLE
collapse/close other sections when a section is opened

### ISSUE THREAD

**Issue by mtabdar** [patosai/tree-multiselect.js#76]
hi
i think it would be useful if there would be an option to close other sections when another section is opened. currently you can open all sections and see the items beneath them but in long lists it can be a bit bothering and you want to collapse all sections but the one you are working with. 
thanks

**Comment by patosai** [comment]
I think the feature set for this plugin is good enough, and this would qualify as something you can accomplish by having an `onChange` function. Just find open sections inside this functions and do a `.click()` on them.
