### ISSUE TITLE
title class add id

### ISSUE THREAD

**Issue by serhathalil** [patosai/tree-multiselect.js#79]
Hi, i want to take id title class(data-section) and if user select all of child checkbox, i will get only parent's (data-section's) id. How can i do it?  Thank you?

**Comment by patosai** [comment]
I don't understand, there are no public IDs for the stuff in the tree.

**Comment by serhathalil** [comment]
for example;

https://jsfiddle.net/85tbxmaq/3/

may be i will add  "id: astSection.id " at line 1139  like this;
var titleNode = exports.createNode('div', { class: 'title', text: astSection.name, id: astSection.id });
  if (createCheckboxes) {
    var checkboxProps = {
      class: 'section',
      type: 'checkbox'
    };

**Comment by patosai** [comment]
This is not possible right now, the plugin would need to add 'fake' options to the original $select that represent the sections. That way, the values can still be retrieved with $select.val() to preserve backwards compatibility.
