### ISSUE TITLE
all checked but just a few are in the source option

### ISSUE THREAD

**Issue by newzen** [patosai/tree-multiselect.js#8]
Hey,
Great job. Have a issue with it http://jsfiddle.net/newzen/nftdvyk4/3/ all checked but just a few are in the source option.

any help will be appreciated, thanks

**Comment by patosai** [comment]
What source option?

**Comment by patosai** [comment]
One thing I'm noticing though, is the lack of `value` attrs on the options. If you don't have those, I think the option text will be sent instead and those aren't unique in this case.

**Comment by newzen** [comment]
corrected, all work now. http://jsfiddle.net/newzen/nftdvyk4/6/
Maybe you can document value attrs is required.

thanks for your help

**Comment by msaah85** [comment]
How i can set my custom selected options after loading the tree?

**Comment by msaah85** [comment]
How i can get all selected nodes by code?
Thanks
