### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by serhathalil** [patosai/tree-multiselect.js#82]
Hi, when i want search somethink, if function find somethink child element's searchit=true but parent element's searchhit=false. if parent element searchhit attribute=false, search result will empty..
 how can i solve it? (I filled data-key from db. ) thanks

 
![image](https://user-images.githubusercontent.com/23178700/76955663-a4ed2c00-6923-11ea-896a-d41bf8e78180.png)

**Comment by patosai** [comment]
got an example?
